# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         App-Widget-ChartDirector
version:      0.60
version_from: 
installdirs:  site
requires:
    App::Options:                  0
    File::Spec:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
