---
name: App-Widget-ChartDirector
version: 0.50
author:
  - stephen.adkins@officevision.com
abstract: A graphing widget which displays graphs and charts for web applications using the ChartDirector graphing library within the App-Context/App-Widget widget framework
license: perl
requires:
  App::Options: 0
build_requires:
  App::Build: 0
  File::Spec: 0
  Module::Build: 0
dynamic_config: 1
provides:
  App::Widget::ChartDirector:
    file: lib/App/Widget/ChartDirector.pm
    version: 3516.
generated_by: Module::Build version 0.2611
